# Generated by Django 6.1.1 on 2026-09-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='proof_file',
            field=models.FileField(blank=True, help_text='The actual receipt/invoice/ticket', null=True, upload_to='proofs/'),
        ),
    ]
