# Generated by Django 6.1.1 on 2026-09-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expenseitem_proof_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='ai_insights_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='ai_insights_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='ai_insights_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
