# Generated by Django 6.1.1 on 2026-09-20 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expenseclaim_ai_insights_content_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='advance_disbursed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='advance_disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='advance_disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_disbursed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='advance_disbursement_ref',
            field=models.CharField(blank=True, help_text='Finance reference e.g. ADV/2026/0619', max_length=100),
        ),
    ]
