# Generated by Django 6.1.1 on 2026-09-20 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_travelrequest_advance_disbursed_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='advance_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='advance_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='advance_review_note',
            field=models.TextField(blank=True, help_text="Finance's reason for holding advance disbursement"),
        ),
    ]
