# Generated by Django 6.1.1 on 2026-09-20 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_travelrequest_advance_review_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TRApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('manager', 'Reporting Manager'), ('dept_head', 'Head of Department'), ('div_head', 'Head of Division'), ('md_ceo', 'MD/CEO')], max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tr_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_chain', to='core.travelrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('travel_request', 'level')},
            },
        ),
    ]
